apiVersion: extensions.istio.io/v1alpha1
kind: WasmPlugin
metadata:
  name: coraza-waf-gateway
spec:
  # We only need a selector in case this is an app injection, not namespace
  selector:
    matchLabels:
      app: istio-gateway
  url: oci://ghcr.io/corazawaf/coraza-proxy-wasm:0.4.0
  imagePullPolicy: IfNotPresent
  phase: AUTHN
  pluginConfig:
    rules: |
      Include @recommended-conf
      # We set this On to test it worked
      # After testing we should change it to DetectionOnly
      SecRuleEngine On
      Include @crs-setup-conf
      Include @owasp_crs/*.conf