apiVersion: v1
kind: Secret
metadata:
  name: "external-dns-{{.Env.ARGOCD_ENV_NAME_PREFIX}}"
stringData:
  azure.json: |
    {
      "tenantId": "{{.Env.ARGOCD_ENV_TENANT_ID}}",
      "subscriptionId": "{{.Env.ARGOCD_ENV_SUBSCRIPTION_ID}}",
      "resourceGroup": "{{.Env.ARGOCD_ENV_RESOURCE_GROUP_NAME}}",
      "useWorkloadIdentityExtension": true
    }

type: Opaque
