apiVersion: v1
kind: Service
metadata:
  name: "external-dns-{{.Env.ARGOCD_ENV_NAME_PREFIX}}"
  labels:
    app.kubernetes.io/name: "external-dns-{{.Env.ARGOCD_ENV_NAME_PREFIX}}"
spec:
  ports:
    - name: http
      port: 7979
      protocol: TCP
      targetPort: http
  selector:
    app.kubernetes.io/name: "external-dns-{{.Env.ARGOCD_ENV_NAME_PREFIX}}"
  type: ClusterIP
