apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: "{{.Env.ARGOCD_ENV_NAMESPACE}}"

resources:
  - deployment.yaml
  - rbac.yaml
  - secret.yaml
  - serviceaccount.yaml
  - service.yaml
