apiVersion: v1
kind: Service
metadata:
  labels:
    app: snapcd-cache
  name: snapcd-cache
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: snapcd-cache
  sessionAffinity: None
  type: ClusterIP