apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
  name: snapcd
spec:
  provider:
    azurekv:
      authType: WorkloadIdentity
      vaultUrl: "{{ .Env.ARGOCD_ENV_AKV_URL }}"
      serviceAccountRef:
        name: snapcd
