---
# Source: gateway/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: istio-gateway-daemon-set
  namespace: istio-gateway
  labels:
    helm.sh/chart: gateway-1.22.0
    app: istio-gateway-daemon-set
    istio: gateway-daemon-set
    app.kubernetes.io/version: "1.22.0"
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: istio-gateway-daemon-set
---
# Source: gateway/templates/role.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: istio-gateway-daemon-set
  namespace: istio-gateway
  labels:
    helm.sh/chart: gateway-1.22.0
    app: istio-gateway-daemon-set
    istio: gateway-daemon-set
    app.kubernetes.io/version: "1.22.0"
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: istio-gateway-daemon-set
  annotations:
    {}
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get", "watch", "list"]
---
# Source: gateway/templates/role.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: istio-gateway-daemon-set
  namespace: istio-gateway
  labels:
    helm.sh/chart: gateway-1.22.0
    app: istio-gateway-daemon-set
    istio: gateway-daemon-set
    app.kubernetes.io/version: "1.22.0"
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: istio-gateway-daemon-set
  annotations:
    {}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: istio-gateway-daemon-set
subjects:
- kind: ServiceAccount
  name: istio-gateway-daemon-set
---
# Source: gateway/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: istio-gateway-daemon-set
  namespace: istio-gateway
  labels:
    helm.sh/chart: gateway-1.22.0
    app: istio-gateway-daemon-set
    istio: gateway-daemon-set
    app.kubernetes.io/version: "1.22.0"
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: istio-gateway-daemon-set
  annotations:
    {}
spec:
  externalTrafficPolicy: "Local"
  type: LoadBalancer
  ports:
    - name: status-port
      port: 15021
      protocol: TCP
      targetPort: 15021
    - name: http2
      port: 80
      protocol: TCP
      targetPort: 80
    - name: https
      port: 443
      protocol: TCP
      targetPort: 443
  selector:
    app: istio-gateway-daemon-set
    istio: gateway-daemon-set
---
# Source: gateway/templates/deployment.yaml
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: istio-gateway-daemon-set
  namespace: istio-gateway
  labels:
    helm.sh/chart: gateway-1.22.0
    app: istio-gateway-daemon-set
    istio: gateway-daemon-set
    app.kubernetes.io/version: "1.22.0"
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: istio-gateway-daemon-set
  annotations:
    {}
spec:
  selector:
    matchLabels:
      app: istio-gateway-daemon-set
      istio: gateway-daemon-set
  template:
    metadata:
      annotations:
        inject.istio.io/templates: gateway
        prometheus.io/path: /stats/prometheus
        prometheus.io/port: "15020"
        prometheus.io/scrape: "true"
        sidecar.istio.io/inject: "true"
      labels:
        sidecar.istio.io/inject: "true"
        app: istio-gateway-daemon-set
        istio: gateway-daemon-set
    spec:
      serviceAccountName: istio-gateway-daemon-set
      securityContext:
        # Safe since 1.22: https://github.com/kubernetes/kubernetes/pull/103326
        sysctls:
        - name: net.ipv4.ip_unprivileged_port_start
          value: "0"
      containers:
        - name: istio-proxy
          # "auto" will be populated at runtime by the mutating webhook. See https://istio.io/latest/docs/setup/additional-setup/sidecar-injection/#customizing-injection
          image: auto
          securityContext:
            capabilities:
              drop:
              - ALL
            allowPrivilegeEscalation: false
            privileged: false
            readOnlyRootFilesystem: true
            runAsUser: 1337
            runAsGroup: 1337
            runAsNonRoot: true
          env:
          ports:
          - containerPort: 15090
            protocol: TCP
            name: http-envoy-prom
          resources:
            limits:
              cpu: 2000m
              memory: 1024Mi
            requests:
              cpu: 100m
              memory: 128Mi
      tolerations:
        - effect: NoSchedule
          key: kubernetes.azure.com/scalesetpriority
          operator: Equal
          value: spot
      terminationGracePeriodSeconds: 30
