apiVersion: v1
kind: Namespace
metadata:
  name: istio-gateway
  labels:
    istio-injection: enabled

  annotations:
    scheduler.alpha.kubernetes.io/defaultTolerations: "{{.Env.ARGOCD_ENV_NAMESPACE_TOLERATIONS}}"
    scheduler.alpha.kubernetes.io/node-selector: "priority={{.Env.ARGOCD_ENV_NAMESPACE_NODE_PRIORITY}}"
