apiVersion: apps/v1
kind: Deployment
metadata:
  name: istiod
  namespace: istio-system
spec:
  template:
    spec:
      $patch: delete
      nodeSelector:
        priority: "{{.Env.ARGOCD_ENV_NODE_PRIORITY}}"
