apiVersion: v1
kind: ServiceAccount
metadata:
  name: cert-manager
  namespace: cert-manager
  labels:
    azure.workload.identity/use: "true"
  annotations:
    azure.workload.identity/client-id: "{{.Env.ARGOCD_ENV_AWI_CLIENT_ID}}"
    azure.workload.identity/tenant-id: "{{.Env.ARGOCD_ENV_TENANT_ID}}"
    azure.workload.identity/service-account-token-expiration: "86400" # Token is valid for 1 day
