apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
  name: "influxdb-{{.Env.ARGOCD_ENV_INFLUXDB_SECRET_HASH}}"
spec:
  refreshInterval: 5m
  secretStoreRef:
    kind: SecretStore
    name: influxdb
  target:
    name: "influxdb-{{.Env.ARGOCD_ENV_INFLUXDB_SECRET_HASH}}"
    creationPolicy: Owner
  data:
    - secretKey: DOCKER_INFLUXDB_INIT_USERNAME
      remoteRef:
        key: "secret/influxdb-init-username"
    - secretKey: DOCKER_INFLUXDB_INIT_PASSWORD
      remoteRef:
        key: "secret/influxdb-init-password"
    - secretKey: DOCKER_INFLUXDB_INIT_TOKEN
      remoteRef:
        key: "secret/influxdb-init-token"

