apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
  name: "snapcd-{{.Env.ARGOCD_ENV_SNAPCD_SECRET_HASH}}"
spec:
  refreshInterval: 5m
  secretStoreRef:
    kind: SecretStore
    name: snapcd
  target:
    name: "snapcd-{{.Env.ARGOCD_ENV_SNAPCD_SECRET_HASH}}"
    creationPolicy: Owner
  data:
    - secretKey: DatabaseSettings__ConnectionString
      remoteRef:
        key: "secret/snapcd-database-settings-connection-string"
    - secretKey: InfluxDbLogStore_Token
      remoteRef:
        key: "secret/snapcd-influxdb-logstore-token"
    - secretKey: EmailSender__Sendgrid__ApiKey
      remoteRef:
        key: "secret/snapcd-email-sender-sendgrid-api-key"
    - secretKey: OpenIdConnect__ExternalLoginProviders__AzureAd__ClientCredentials__0__ClientSecret
      remoteRef:
        key: "secret/snapcd-azure-ad-client-secret"
    - secretKey: DataSeeder__AdminServicePrincipal__ClientSecret
      remoteRef:
        key: "secret/snapcd-data-seeder-admin-service-principal-client-secret"
    - secretKey: LicenseVerification__LicenseKey
      remoteRef:
        key: "secret/snapcd-license-verification-licence-key"