apiVersion: v1
kind: ServiceAccount
metadata:
  name: snapcd
  labels:
    app.kubernetes.io/name: snapcd
    app.kubernetes.io/instance: snapcd
    azure.workload.identity/use: "true"
  annotations:
    argocd.argoproj.io/sync-wave: "-3"
    azure.workload.identity/client-id: "{{.Env.ARGOCD_ENV_AWI_CLIENT_ID}}"
    azure.workload.identity/tenant-id: "{{.Env.ARGOCD_ENV_TENANT_ID}}"
    azure.workload.identity/service-account-token-expiration: "86400" # Token is valid for 1 day
automountServiceAccountToken: true
